//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.17 at 01:20:51 PM BST 
//


package psidev.psi.ms.mzml.mapping.jaxb;

import org.w3c.dom.Element;
import org.w3c.dom.Document;
import org.w3c.dom.NodeList;
import org.w3c.dom.Node;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.DocumentBuilder;
import java.io.ByteArrayInputStream;


/**
 * Description of the components of the mass spectrometer used
 * 
 * <p>Java class for InstrumentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InstrumentType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://psi.hupo.org/schema_revision/mzML_0.93}ParamGroupType">
 *       &lt;sequence>
 *         &lt;element name="componentList" type="{http://psi.hupo.org/schema_revision/mzML_0.93}ComponentListType"/>
 *         &lt;element name="instrumentSoftwareRef" type="{http://psi.hupo.org/schema_revision/mzML_0.93}InstrumentSoftwareRefType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InstrumentType", propOrder = {
    "componentList",
    "instrumentSoftwareRef"
})
public class InstrumentType
    extends ParamGroupType
{

    @XmlElement(required = true)
    protected ComponentListType componentList;
    protected InstrumentSoftwareRefType instrumentSoftwareRef;
    @XmlAttribute(required = true)
    protected String id;


    private String elementName = "instrument";

    public InstrumentType() {}

    public InstrumentType(String xmlSnippet) {
        parseXml(xmlSnippet);
    }

    public InstrumentType(Element element) {
        create(element);
    }

    ///////////////////
    // utilities

    private void parseXml(String xmlSnippet) {
        Document document = null;
        try {
            DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
            DocumentBuilder builder = factory.newDocumentBuilder();
            ByteArrayInputStream str = new ByteArrayInputStream(xmlSnippet.getBytes());
            document = builder.parse( str );
        } catch ( Exception e ) {
            e.printStackTrace();
        }


        // we always expect a String representing a single xml tag, not a list of xml tags!
        if (document != null) {
            NodeList nl = document.getElementsByTagName(elementName);
            if (nl.getLength() == 1) {
                Element ele = (Element) nl.item(0);
                create(ele);
            } else {
                throw new IllegalStateException("Expected only one '" + elementName + "' element, but found: " + nl.getLength());
            }
        }

    }

    protected void create(Node node) {
        Element ele = (Element) node;
        if (ele != null) {
            // load attributes
            String id = ele.getAttribute("id");
            if (!id.equals("")) { // getAttribute returns empty String if no value was specified
                setId(id);
            }
            // load elements
            NodeList nl = ele.getElementsByTagName("componentList");
            // we only expect one such element!
            if (nl.getLength() == 1) {
                componentList = new ComponentListType((Element) nl.item(0));
            } else {
                throw new IllegalStateException("Expected only one 'componentList' element, but found: " + nl.getLength());
            }
            nl = null;
            nl = ele.getElementsByTagName("instrumentSoftwareRef");
            if (nl.getLength() == 1) {
                instrumentSoftwareRef = new InstrumentSoftwareRefType((Element) nl.item(0));
            } else {
                throw new IllegalStateException("Expected only one 'instrumentSoftwareRef' element, but found: " + nl.getLength());
            }
            // inherited form ParamGroupType
            super.create(node);
        }
    }

    ////////////////////
    // Getter + Setter

    /**
     * Gets the value of the componentList property.
     * 
     * @return
     *     possible object is
     *     {@link ComponentListType }
     *     
     */
    public ComponentListType getComponentList() {
        return componentList;
    }

    /**
     * Sets the value of the componentList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComponentListType }
     *     
     */
    public void setComponentList(ComponentListType value) {
        this.componentList = value;
    }

    /**
     * Gets the value of the instrumentSoftwareRef property.
     * 
     * @return
     *     possible object is
     *     {@link InstrumentSoftwareRefType }
     *     
     */
    public InstrumentSoftwareRefType getInstrumentSoftwareRef() {
        return instrumentSoftwareRef;
    }

    /**
     * Sets the value of the instrumentSoftwareRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstrumentSoftwareRefType }
     *     
     */
    public void setInstrumentSoftwareRef(InstrumentSoftwareRefType value) {
        this.instrumentSoftwareRef = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
