//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.17 at 01:20:51 PM BST 
//


package psidev.psi.ms.mzml.mapping.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the psidev.psi.ms.mzml.mapping.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MzML_QNAME = new QName("http://psi.hupo.org/schema_revision/mzML_0.93", "mzML");
    private final static QName _ComponentListTypeSource_QNAME = new QName("http://psi.hupo.org/schema_revision/mzML_0.93", "source");
    private final static QName _ComponentListTypeAnalyzer_QNAME = new QName("http://psi.hupo.org/schema_revision/mzML_0.93", "analyzer");
    private final static QName _ComponentListTypeDetector_QNAME = new QName("http://psi.hupo.org/schema_revision/mzML_0.93", "detector");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: psidev.psi.ms.mzml.mapping.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RunType.SourceFileRefList.SourceFileRef }
     * 
     */
    public RunType.SourceFileRefList.SourceFileRef createRunTypeSourceFileRefListSourceFileRef() {
        return new RunType.SourceFileRefList.SourceFileRef();
    }

    /**
     * Create an instance of {@link InstrumentSoftwareRefType }
     * 
     */
    public InstrumentSoftwareRefType createInstrumentSoftwareRefType() {
        return new InstrumentSoftwareRefType();
    }

    /**
     * Create an instance of {@link SpectrumDescriptionType.Scan.SelectionWindowList }
     * 
     */
    public SpectrumDescriptionType.Scan.SelectionWindowList createSpectrumDescriptionTypeScanSelectionWindowList() {
        return new SpectrumDescriptionType.Scan.SelectionWindowList();
    }

    /**
     * Create an instance of {@link SampleType }
     * 
     */
    public SampleType createSampleType() {
        return new SampleType();
    }

    /**
     * Create an instance of {@link AcquisitionListType }
     * 
     */
    public AcquisitionListType createAcquisitionListType() {
        return new AcquisitionListType();
    }

    /**
     * Create an instance of {@link DataProcessingType.ProcessingMethod }
     * 
     */
    public DataProcessingType.ProcessingMethod createDataProcessingTypeProcessingMethod() {
        return new DataProcessingType.ProcessingMethod();
    }

    /**
     * Create an instance of {@link InstrumentListType }
     * 
     */
    public InstrumentListType createInstrumentListType() {
        return new InstrumentListType();
    }

    /**
     * Create an instance of {@link CVListType }
     * 
     */
    public CVListType createCVListType() {
        return new CVListType();
    }

    /**
     * Create an instance of {@link ParamGroupRefType }
     * 
     */
    public ParamGroupRefType createParamGroupRefType() {
        return new ParamGroupRefType();
    }

    /**
     * Create an instance of {@link CVParamType }
     * 
     */
    public CVParamType createCVParamType() {
        return new CVParamType();
    }

    /**
     * Create an instance of {@link ComponentType }
     * 
     */
    public ComponentType createComponentType() {
        return new ComponentType();
    }

    /**
     * Create an instance of {@link ReferenceableParamGroupListType }
     * 
     */
    public ReferenceableParamGroupListType createReferenceableParamGroupListType() {
        return new ReferenceableParamGroupListType();
    }

    /**
     * Create an instance of {@link SourceFileType }
     * 
     */
    public SourceFileType createSourceFileType() {
        return new SourceFileType();
    }

    /**
     * Create an instance of {@link ComponentListType }
     * 
     */
    public ComponentListType createComponentListType() {
        return new ComponentListType();
    }

    /**
     * Create an instance of {@link ReferenceableParamGroupType }
     * 
     */
    public ReferenceableParamGroupType createReferenceableParamGroupType() {
        return new ReferenceableParamGroupType();
    }

    /**
     * Create an instance of {@link DataProcessingType }
     * 
     */
    public DataProcessingType createDataProcessingType() {
        return new DataProcessingType();
    }

    /**
     * Create an instance of {@link FileDescriptionType }
     * 
     */
    public FileDescriptionType createFileDescriptionType() {
        return new FileDescriptionType();
    }

    /**
     * Create an instance of {@link SoftwareType }
     * 
     */
    public SoftwareType createSoftwareType() {
        return new SoftwareType();
    }

    /**
     * Create an instance of {@link AcquisitionType }
     * 
     */
    public AcquisitionType createAcquisitionType() {
        return new AcquisitionType();
    }

    /**
     * Create an instance of {@link CVType }
     * 
     */
    public CVType createCVType() {
        return new CVType();
    }

    /**
     * Create an instance of {@link MzMLType }
     * 
     */
    public MzMLType createMzMLType() {
        return new MzMLType();
    }

    /**
     * Create an instance of {@link SpectrumDescriptionType.Scan }
     * 
     */
    public SpectrumDescriptionType.Scan createSpectrumDescriptionTypeScan() {
        return new SpectrumDescriptionType.Scan();
    }

    /**
     * Create an instance of {@link SpectrumType }
     * 
     */
    public SpectrumType createSpectrumType() {
        return new SpectrumType();
    }

    /**
     * Create an instance of {@link SampleListType }
     * 
     */
    public SampleListType createSampleListType() {
        return new SampleListType();
    }

    /**
     * Create an instance of {@link ScanType }
     * 
     */
    public ScanType createScanType() {
        return new ScanType();
    }

    /**
     * Create an instance of {@link SoftwareListType.Software }
     * 
     */
    public SoftwareListType.Software createSoftwareListTypeSoftware() {
        return new SoftwareListType.Software();
    }

    /**
     * Create an instance of {@link SourceFileListType }
     * 
     */
    public SourceFileListType createSourceFileListType() {
        return new SourceFileListType();
    }

    /**
     * Create an instance of {@link SoftwareListType.Software.SoftwareParam }
     * 
     */
    public SoftwareListType.Software.SoftwareParam createSoftwareListTypeSoftwareSoftwareParam() {
        return new SoftwareListType.Software.SoftwareParam();
    }

    /**
     * Create an instance of {@link FileChecksumType }
     * 
     */
    public FileChecksumType createFileChecksumType() {
        return new FileChecksumType();
    }

    /**
     * Create an instance of {@link SpectrumListType }
     * 
     */
    public SpectrumListType createSpectrumListType() {
        return new SpectrumListType();
    }

    /**
     * Create an instance of {@link SpectrumDescriptionType }
     * 
     */
    public SpectrumDescriptionType createSpectrumDescriptionType() {
        return new SpectrumDescriptionType();
    }

    /**
     * Create an instance of {@link PrecursorListType }
     * 
     */
    public PrecursorListType createPrecursorListType() {
        return new PrecursorListType();
    }

    /**
     * Create an instance of {@link DataProcessingListType }
     * 
     */
    public DataProcessingListType createDataProcessingListType() {
        return new DataProcessingListType();
    }

    /**
     * Create an instance of {@link PrecursorType }
     * 
     */
    public PrecursorType createPrecursorType() {
        return new PrecursorType();
    }

    /**
     * Create an instance of {@link ContactType }
     * 
     */
    public ContactType createContactType() {
        return new ContactType();
    }

    /**
     * Create an instance of {@link BinaryDataArrayType }
     * 
     */
    public BinaryDataArrayType createBinaryDataArrayType() {
        return new BinaryDataArrayType();
    }

    /**
     * Create an instance of {@link RunType }
     * 
     */
    public RunType createRunType() {
        return new RunType();
    }

    /**
     * Create an instance of {@link UserParamType }
     * 
     */
    public UserParamType createUserParamType() {
        return new UserParamType();
    }

    /**
     * Create an instance of {@link RunType.SourceFileRefList }
     * 
     */
    public RunType.SourceFileRefList createRunTypeSourceFileRefList() {
        return new RunType.SourceFileRefList();
    }

    /**
     * Create an instance of {@link SpectrumDescriptionType.Scan.SelectionWindowList.SelectionWindow }
     * 
     */
    public SpectrumDescriptionType.Scan.SelectionWindowList.SelectionWindow createSpectrumDescriptionTypeScanSelectionWindowListSelectionWindow() {
        return new SpectrumDescriptionType.Scan.SelectionWindowList.SelectionWindow();
    }

    /**
     * Create an instance of {@link ParamGroupType }
     * 
     */
    public ParamGroupType createParamGroupType() {
        return new ParamGroupType();
    }

    /**
     * Create an instance of {@link InstrumentType }
     * 
     */
    public InstrumentType createInstrumentType() {
        return new InstrumentType();
    }

    /**
     * Create an instance of {@link SoftwareListType }
     * 
     */
    public SoftwareListType createSoftwareListType() {
        return new SoftwareListType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MzMLType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://psi.hupo.org/schema_revision/mzML_0.93", name = "mzML")
    public JAXBElement<MzMLType> createMzML(MzMLType value) {
        return new JAXBElement<MzMLType>(_MzML_QNAME, MzMLType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComponentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://psi.hupo.org/schema_revision/mzML_0.93", name = "source", scope = ComponentListType.class)
    public JAXBElement<ComponentType> createComponentListTypeSource(ComponentType value) {
        return new JAXBElement<ComponentType>(_ComponentListTypeSource_QNAME, ComponentType.class, ComponentListType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComponentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://psi.hupo.org/schema_revision/mzML_0.93", name = "analyzer", scope = ComponentListType.class)
    public JAXBElement<ComponentType> createComponentListTypeAnalyzer(ComponentType value) {
        return new JAXBElement<ComponentType>(_ComponentListTypeAnalyzer_QNAME, ComponentType.class, ComponentListType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComponentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://psi.hupo.org/schema_revision/mzML_0.93", name = "detector", scope = ComponentListType.class)
    public JAXBElement<ComponentType> createComponentListTypeDetector(ComponentType value) {
        return new JAXBElement<ComponentType>(_ComponentListTypeDetector_QNAME, ComponentType.class, ComponentListType.class, value);
    }

}
