//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.17 at 01:20:51 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://psi.hupo.org/schema_revision/mzML_0.93", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package psidev.psi.ms.mzml.mapping.jaxb;
