//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.17 at 01:20:51 PM BST 
//


package psidev.psi.ms.mzml.mapping.jaxb;

import org.w3c.dom.Element;
import org.w3c.dom.Document;
import org.w3c.dom.NodeList;
import org.w3c.dom.Node;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.DocumentBuilder;
import java.io.ByteArrayInputStream;


/**
 * The method of precursor ion selection and activation
 * 
 * <p>Java class for PrecursorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PrecursorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ionSelection" type="{http://psi.hupo.org/schema_revision/mzML_0.93}ParamGroupType"/>
 *         &lt;element name="activation" type="{http://psi.hupo.org/schema_revision/mzML_0.93}ParamGroupType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="spectrumRef" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PrecursorType", propOrder = {
    "ionSelection",
    "activation"
})
public class PrecursorType {

    @XmlElement(required = true)
    protected ParamGroupType ionSelection;
    @XmlElement(required = true)
    protected ParamGroupType activation;
    @XmlAttribute
    protected String spectrumRef;


    private String elementName = "precursor";

    public PrecursorType() {}

    public PrecursorType(String xmlSnippet) {
        parseXml(xmlSnippet);
    }

    public PrecursorType(Element element) {
        create(element);
    }

    ///////////////////
    // utilities

    private void parseXml(String xmlSnippet) {
        Document document = null;
        try {
            DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
            DocumentBuilder builder = factory.newDocumentBuilder();
            ByteArrayInputStream str = new ByteArrayInputStream(xmlSnippet.getBytes());
            document = builder.parse( str );
        } catch ( Exception e ) {
            e.printStackTrace();
        }


        // we always expect a String representing a single xml tag, not a list of xml tags!
        if (document != null) {
            NodeList nl = document.getElementsByTagName(elementName);
            if (nl.getLength() == 1) {
                Element ele = (Element) nl.item(0);
                create(ele);
            } else {
                throw new IllegalStateException("Expected only one '" + elementName + "' element, but found: " + nl.getLength());
            }
        }

    }

    private void create(Node node) {
        Element ele = (Element) node;
        if (ele != null) {
            // load attributes
            String spectrumRef = ele.getAttribute("spectrumRef");
            if (!spectrumRef.equals("")) { // getAttribute returns empty String if no value was specified
                setSpectrumRef(spectrumRef);
            }

            // create other elements
            NodeList nl = ele.getElementsByTagName("ionSelection");
            // we only expect one such element!
            if (nl.getLength() == 1) {
                ionSelection = new ParamGroupType((Element) nl.item(0));
            } else {
                throw new IllegalStateException("Expected only one 'ionSelection' element, but found: " + nl.getLength());
            }
            nl = null;
            nl = ele.getElementsByTagName("activation");
            // we only expect one such element!
            if (nl.getLength() == 1) {
                activation = new ParamGroupType((Element) nl.item(0));
            } else {
                throw new IllegalStateException("Expected only one 'activation' element, but found: " + nl.getLength());
            }

        }
    }

    ////////////////////
    // Getter + Setter

    /**
     * Gets the value of the ionSelection property.
     * 
     * @return
     *     possible object is
     *     {@link ParamGroupType }
     *     
     */
    public ParamGroupType getIonSelection() {
        return ionSelection;
    }

    /**
     * Sets the value of the ionSelection property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParamGroupType }
     *     
     */
    public void setIonSelection(ParamGroupType value) {
        this.ionSelection = value;
    }

    /**
     * Gets the value of the activation property.
     * 
     * @return
     *     possible object is
     *     {@link ParamGroupType }
     *     
     */
    public ParamGroupType getActivation() {
        return activation;
    }

    /**
     * Sets the value of the activation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParamGroupType }
     *     
     */
    public void setActivation(ParamGroupType value) {
        this.activation = value;
    }

    /**
     * Gets the value of the spectrumRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpectrumRef() {
        return spectrumRef;
    }

    /**
     * Sets the value of the spectrumRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpectrumRef(String value) {
        this.spectrumRef = value;
    }

}
