//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.02 at 01:22:10 PM CET 
//


package psidev.psi.ms.rulefilter.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="mzIdentMLElement" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "mandatoryMzIdentMLElement")
public class MandatoryMzIdentMLElement {

    @XmlAttribute(name = "mzIdentMLElement", required = true)
    protected String mzIdentMLElement;

    /**
     * Gets the value of the mzIdentMLElement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMzIdentMLElement() {
        return mzIdentMLElement;
    }

    /**
     * Sets the value of the mzIdentMLElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMzIdentMLElement(String value) {
        this.mzIdentMLElement = value;
    }

}
