//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.02 at 01:22:10 PM CET 
//


package psidev.psi.ms.rulefilter.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}objectRuleToSkip" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}cvMappingRuleToSkip" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="valid" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "objectRuleToSkip",
    "cvMappingRuleToSkip"
})
@XmlRootElement(name = "objectRuleCondition")
public class ObjectRuleCondition {

    protected List<ObjectRuleToSkip> objectRuleToSkip;
    protected List<CvMappingRuleToSkip> cvMappingRuleToSkip;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "valid", required = true)
    protected boolean valid;

    /**
     * Gets the value of the objectRuleToSkip property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the objectRuleToSkip property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObjectRuleToSkip().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObjectRuleToSkip }
     * 
     * 
     */
    public List<ObjectRuleToSkip> getObjectRuleToSkip() {
        if (objectRuleToSkip == null) {
            objectRuleToSkip = new ArrayList<ObjectRuleToSkip>();
        }
        return this.objectRuleToSkip;
    }

    /**
     * Gets the value of the cvMappingRuleToSkip property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cvMappingRuleToSkip property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCvMappingRuleToSkip().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CvMappingRuleToSkip }
     * 
     * 
     */
    public List<CvMappingRuleToSkip> getCvMappingRuleToSkip() {
        if (cvMappingRuleToSkip == null) {
            cvMappingRuleToSkip = new ArrayList<CvMappingRuleToSkip>();
        }
        return this.cvMappingRuleToSkip;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the valid property.
     * 
     */
    public boolean isValid() {
        return valid;
    }

    /**
     * Sets the value of the valid property.
     * 
     */
    public void setValid(boolean value) {
        this.valid = value;
    }

}
